name: dhttpd
version: 3.0.0

description: A static file HTTP server for easy directory serving.
authors:
- Seth Ladd <sethladd@gmail.com>
- Kevin Moore <github@j832.com>
homepage: https://github.com/kevmoo/dhttpd

environment:
  sdk: '>=2.0.0-dev.48.0 <3.0.0'

dependencies:
  args: '>=0.12.0+1 <2.0.0'
  build_cli_annotations: ^0.1.0
  shelf: ^0.7.2
  shelf_static: ^0.2.0

dev_dependencies:
  build_cli: ^0.2.0
  build_runner: ^0.9.0
  path: ^1.6.1
  test: ^1.3.0
  test_process: ^1.0.1

executables:
  dhttpd:
