name: dhttpd
description: A static file HTTP server for easy directory serving.
version: 2.0.0-dev
homepage: https://github.com/kevmoo/dhttpd
authors:
- Seth Ladd <sethladd@gmail.com>
- Kevin Moore <github@j832.com>

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  args: ">=0.12.0+1 <2.0.0"
  shelf: ^0.7.2
  shelf_static: ^0.2.0

executables:
  dhttpd:
