name: simple_http_server
description: A static file HTTP server for easy directory serving.
version: 0.3.1
homepage: https://github.com/sethladd/simple_http_server
authors:
- Seth Ladd <sethladd@gmail.com>

environment:
  sdk: ">=1.6.0 <2.0.0"

dependencies:
  shelf_static: ">=0.2.0 <0.3.0"
  shelf_cors: ">=0.2.0 <0.3.0"
  args: ">=0.12.0+1 <0.14.0"

executables:
  simple_http_server:
  dhttpd:
